Updating minimal changes to handle a possible nil
Datadog has an error AskVAApi::Inquiries::InquiriesCreatorError: InquiriesCreatorError: undefined method `[]' for nil. Adding defensive checks.