Upgrade to Sidekiq 7 (w/ working feature toggles) (#16047)
* Upgrade to Sidekiq 7

This reverts commit 24571c6868c19461f7df313f05b66161d6d34b81 to restore
Sidekiq 7.

* fix: Don't pass nil to redis-client

Sidekiq 7 required the redis gem version 5.x (we were using 4.8) which
required redis-client. redis-client would throw an exception when
searching for a nil key.

This resolves the issue with /v0/feature_toggles experienced Mar 21st.
The exception in Datadog[1] was:

```
TypeError: Unsupported command argument type: NilClass
/usr/local/bundle/cache/ruby/3.2.0/gems/redis-client-0.20.0/lib/redis_client/command_builder.rb:37:in
`block in generate': Unsupported command argument type: NilClass
(TypeError)
...
from /app/lib/common/models/redis_store.rb:51:in `find'
from /app/app/controllers/concerns/authentication_and_sso_concerns.rb:131:in `set_session_object'
from /app/app/controllers/concerns/authentication_and_sso_concerns.rb:67:in `load_user'
```

Following the stack trace, I opened redis-client (`bundle open
redis-client`) and saw that `nil` wasn't supported as a type in the
`case` (command_builder.rb:37) but our redis_store.rb allowed nil to be
passed.

[1]: https://vagov.ddog-gov.com/apm/error-tracking?query=env%3Aeks-prod&fromUser=false&issueId=b8ee5258-e6f4-11ee-b6c6-da7ad0900007&refresh_mode=sliding&sp=&view=spans&from_ts=1711055100302&to_ts=1711058700302&live=true

* Switch Redis config back to to_h