Creates and applies notification.rb enum constants  (#2994)
* Informs future devs how to maintain eligible HCA enrollment statuses

* Creates constants for enum values that can be called elsewhere

For example:

irb(main):001:0> Notification.subjects
=> {"form_10_10ez"=>0, "dashboard_health_care_application_notification"=>1}

irb(main):002:0> Notification::FORM_10_10EZ
NameError: uninitialized constant Notification::FORM_10_10EZ

* Favors using new Notification constants

* Moves eligible status definition into related module

Now that the source of truth is notification.rb, parsed_statuses.rb is no longer needed as the source of truth for these statuses, around the codebase.