Fix undefined method send_failure_email for VeteranReadinessEmploymentClaim
The BenefitsIntakeStatusJob was calling send_failure_email on
SavedClaim::VeteranReadinessEmploymentClaim, which does not have this
method defined. This caused job failures with the error:

undefined method `send_failure_email' for an instance of
SavedClaim::VeteranReadinessEmploymentClaim

Changes:
- Use claim.send_email(:error) instead of claim.send_failure_email(email)
  to leverage the existing VRE::NotificationEmail infrastructure
- Update require from 'vre/monitor' to 'vre/vre_monitor'
- Use VRE::VREMonitor consistently throughout the VRE section
- Use log_silent_failure_avoided instead of log_silent_failure_no_confirmation
  since VRE emails have a callback (VRE::NotificationCallback)

The :error email type is already configured in VRE::NotificationEmail with
the proper VA Notify template (form1900_action_needed_email).