Datadog shows an error when attempting to create an Inquiry. Moving Logging to isolate (#22855)
* build_payload may throw an error

* Revert "build_payload may throw an error"

This reverts commit 870102ce656b8c1f6f285ff4fa648d7df7bea226.

* Updating minimal changes to handle a possible nil

Datadog has an error AskVAApi::Inquiries::InquiriesCreatorError: InquiriesCreatorError: undefined method `[]' for nil. Adding defensive checks.