Ensures nil header values are not passed to HTTP client
Under the hood, `net/http/header.rb` calls:

value = value.strip

If value is nil, this errors with:

NoMethodError: undefined method `strip' for nil:NilClass

This fix ensures that nil will not be passed as a value.